version: "3.8"
services:
  nginx:
    container_name: nginx_ip_management_enamul_0042
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./backend:/var/www/html
  php:
    container_name: php_ip_management_enamul_0042
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mysql:8.0.27
    container_name: mysql_ip_management_enamul_0042
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  
  db_test:
    image: mysql:8.0.27
    container_name: mysql_test_ip_management_enamul_0042
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}_test"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - ./database_test/mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_ip_management_enamul_0042
    links:
      - db_test
    environment:
      PMA_HOST: db_test
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
  
